[package]
name = "shitternet-detector"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
ping = "0.4.0"
directories = "4.0.1"
winit = "=0.25"
trayicon = { version = "0.1.3", features = ["winit"] }
open = "2.0.2"